<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fku_songs"
 *
 * Auto generated by Extension Builder 2016-08-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'FKU Songs',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Widmer',
	'author_email' => 'daniel.widmer@fku.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.2.2',
	'constraints' => [
		'depends' => [
			'typo3' => '9.5.0-10.4.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];

/***********************************************
 * Version 2.4.0
 * -------------                    
 * Charts not fixed on last 3 monthts but flexible
 *
 * Version 2.4.1
 * -------------
 * Confusion about ID of language "Andere" corrected
 *
 * Version 2.5.0
 * -------------
 * Adding new songs from frontend
 *
 * Version 2.6.0
 * -------------
 * Adding view "statistics"
 *
 * Version 2.6.1
 * -------------
 * Detailed song information in view "statistics"
 *
 * Version 2.6.2
 * -------------
 * Update for detailed song information in view "statistics"
 * Adding new song not when selecting songs for reporting
 *
 * Version 2.6.3
 * -------------
 * Show action of song allows to see last 3, 6, 12 months usage
 * Status "Anderswo gekauft" added to reporting
 *
 * Version 2.7.0
 * -------------
 * Using session cookies for back action
 * Extended statistics
 *
 * Version 2.7.1
 * -------------
 * RealURL definitions
 * Minor fix for "Zurücksetzen" button in Song->Show
 *
 * Version 2.8.0
 * -------------
 * Search songs by keywords
 * Mini navigation in several list views
 *
 * Version 2.8.1
 * -------------
 * Correction for pageing of keyword search results
 * Added help text for search form "Suchbegriff"
 *
 * Version 2.8.2
 * -------------
 * Use cookies for statistics and charts filter criteria
 * Remove commas from search term
 *
 * Version 2.9.0
 * -------------
 * Added database field "last usage" per song
 * Scheduler object to fill that field
 *
 * Version 2.9.1
 * -------------
 * Direct link to report songs to CCLI in reporting->editEvent
 *
 * Version 2.9.2
 * -------------
 * Target of links to CCLI always in same window (target="...")
 *
 * Version 2.9.3
 * -------------
 * Halflings instead of glyphicon
 *
 * Version 2.9.4
 * -------------
 * Rendering of FlashMessages (preparation for Typo3 version 8.7
 * Height of flags set to "15c" instead of "15"
 *
 * Version 2.10.0
 * --------------
 * Added "Table of content" view
 *
 * Version 2.10.1
 * --------------
 * Corrections for BackButton partial template
 * Tiny changes in templates
 *
 * Version 2.10.2
 * --------------
 * Showing last usage of a song if outside selecte range of months in show action
 * Action to transfer links (from Pydio links to direct download links)
 *
 * Version 2.10.3
 * --------------
 * Link from event show action to planning master show action
 *
 * Version 3.0.0
 * -------------
 * Icons for most models
 * Links as separate model with relation to song instead of four fixed links
 *
 * Version 3.0.1
 * -------------
 * Remove residual information from views originating from old links fields
 * Sorting keywords alphabetically
 *
 * Version 3.0.2
 * -------------
 * Fixed IfInArray viewhelper
 *
 * Version 3.0.3
 * -------------
 * Minor updates in some templates (cosmetic)
 *
 * Version 3.0.4
 * -------------
 * Minor updates in some templates (cosmetic)
 *
 * Version 3.0.5
 * -------------
 * Added tone in results list template partial
 *
 * Version 3.1.0
 * -------------
 * Remove all old code about link... (e.g. Lyrics) in various files and database
 * Slight reword of Alert partial template
 * Corrected typo in Reporting/Satistics.html
 * Linking document now also works for newly created songs
 * Updating links of new or modified songs outsourced to separare function
 * Back button of Song/Show.html (provisorical) only a JavaScript history.back link
 *
 * Version 3.2.0
 * -------------
 * New constant to define time period selection for charts and statistics
 * Use navigation pills instead of simple links for internal navigation
 * Fixed issue of missing flash message if no search result fits the criteria
 * Added development feature of showing last usage per song in TOC view
 *
 * Version 3.3.0
 * -------------
 * Edit in reporting of an event via AJAX with eID
 * Reolaced buttons by nav-pills in Reporting>ShowEvent and Reporting>EditEvent
 * Added link to Reporting>ListEven from Song>List
 *
 * Version 3.3.1
 * -------------
 * Deactivation of realURL definitions
 *
 * Version 3.4.0
 * -------------
 * Sorting of links in Reporting>ShowEvent by link type
 * Last usage in TOC action open for user group "Musik-Admin" instead of only Developper
 * Corrections in form of Song->tocAction and Song->listAction concerning tag <div class="row">
 * Correction in Reporting->newAction to show message if no search result is found
 * Show all so far added songs to reporting event only if next action is newAction
 * Link to add new song in reporting->showEvent (not only in editEvent)
 *
 * Version 3.5.0
 * -------------
 * Optimized XS view of Reporting>List, Reporting->ShowEvent, and Reporting->EditEvent
 * New field in Collection for slide
 * Song->TocAction allows to show/hide (a) author, (b) slide, (c) last usage date
 *
 * Version 3.5.1
 * -------------
 * Minor change in template Reporting>EditEvent
 *
 * Version 3.6.0
 * -------------
 * Last usages of shown song in Song->Show changes interval (3, 6, 12 months) by Javascript instead of releading the page
 * (also solution with AJAX programmed, but not used)
 *
 * Version 4.0.0
 * -------------
 * Added DB field "songtext" for songs, can be entered in Song->Edit, only showed to developer in Song->Show
 * Include status in Reporting->Stattistics if songtext exists or not
 * Fixed that embedded YouTube video is hidden
 * Take over global setting (TypoScript) for available time periods of song history (like statistics)
 *
 * Version 4.1.0
 * -------------
 * Added search parameters to search in songtext
 * List of keywords in Song->Keyword hidden if search results are available (to easier see the results below the keywords list)
 *
 * Version 4.2.0
 * -------------
 * Export of TOC as PDF file (Song->tocExport), needs FDPF
 *
 * Version 4.3.0
 * -------------
 * New field in Song table and model: popularity
 * Scheduler command to calculate popularity
 *
 * Version 4.4.0
 * -------------
 * New fields in Song table and model: usages, statistic_update
 * Scheduler command to calculate usages together with popularity
 * Developper's view for tocAction to see usages and popularity in results
 *
 * Version 4.4.1
 * -------------
 * Minor corrections in SongCommandController for counting the number of usages in the past 24 months
 *
 * Version 4.4.2
 * -------------
 * Added autofocus attribute to song search field template
 * 3-star symbol for popularity in various templates (as a new partial template)
 *
 * Version 4.4.3
 * -------------
 * Scheduler function popularityCommand has new parameter "months"
 *
 * Version 4.4.4
 * -------------
 * Song search results can be sorted by popularity
 *
 * Version 4.4.5
 * -------------
 * Replaced "beliebtes Lied" by "Kernlied" in all templates / partials
 * Make some of the (i.e. popularity index) visible for non-developpers in templates
 *
 * Version 4.5.0
 * -------------
 * Option to show/hide rejected songs in TOC and TOC export
 *
 * Version 4.5.1
 * -------------
 * Optimize song search result table for XS view
 * Hide search options by default in search form
 *
 * Version 4.5.2
 * -------------
 * Use SVG grpahics instead of png for flags
 *
 * Version 4.5.3
 * -------------
 * New viehelper Utf8Encode to encode strings into utf-8
 * Use this viewhelper for title in TOC export title
 *
 * Version 5.0.0
 * -------------
 * "Strophe" is in bold in songtext
 * New song property "copyright" added to replace "publicdomain" and "proprietary" and extend it (new DB field)
 * Adapted many templates and SongController and ReportingController for above change
 *
 * Version 5.0.1
 * -------------
 * Remove of no longer used DB fields "publicdomain" and "proprietary" in model song
 *
 * Version 5.1.0
 * -------------
 * Remove language "unbekannt" for songs
 * Parameter in sources "withrecommended" to specify if source may contain songs with flag "recommended", used for search options of songs
 * Search form with three different modes for predefined search parameters
 *
 * Version 5.1.1
 * -------------
 * Default search options for user-defined mode set identical to Gottesdienst mode
 *
 * Version 5.1.2
 * -------------
 * Added check for variable allSources to remove a bug
 * Set global variables for filter defaults in SongController (preparation for search modes in keywords)
 *
 * Version 5.1.3
 * -------------
 * Removed check for variable allSources in SongRepository because it did not solve the problem
 *
 * Version 5.1.4
 * -------------
 * Modified partial Song/Formfields for rejected button in collections to fix a bug
 *
 * Version 5.2.0
 * -------------
 * New reporting actions "open" and "complete" to close open reportings of same song cross-event
 *
 * Version 5.2.1
 * -------------
 * New value of class Song "songtextCopyright" about the information if songtext can be shown legally
 *
 * Version 5.3.0
 * -------------
 * Filter values in song search form to show or hide four pieces of information
 *
 * Version 5.3.1
 * -------------
 * Clean-up in TCA defintions
 *
 * Version 5.3.2
 * -------------
 * Correct bug: Store new filter values in search form starting with show... in cookies
 * Use font color for copyright icons in partial Song/TextCopyright
 *
 * Version 6.0.0
 * -------------                    
 * Ready for Typo3 version 10
 * Many further updates, e.g. for Bootstrap package 4.5 and Glyphicons 2.4
 *
 * Version 6.0.1
 * -------------                    
 * Minor changes
 *
 * Version 6.0.2
 * -------------                    
 * composer.json added
 * Minor corrections in template TocTable
 * Minor correction in tocExportAction of SongController
 *
 * Version 6.0.3
 * -------------                    
 * Minor correction in template Reporting > Open.html
 *
 * Version 6.1.0
 * -------------                    
 * Use middleware (PSR-15) instead of eID for song reporting status update
 *
 * Version 7.0.0
 * -------------                    
 * Added slugs for songs => database update required!
 * Removed pi_flexform with its switchableControllerActions and created separate plugins (in ext_localconf.php)
 * Typoscript (constants and setup) in plugin.tx_fkusongs instead of plugin.tx_fkusongs_songs
 * Define dependency injections with Service.yaml, remove Commands.php to define scheduler tasks
 *
 * Version 7.0.1
 * -------------                    
 * Bugfix: adding keywords to songs did not work
 *
 * Version 7.1.0
 * -------------                    
 * Rename constants.txt and setup.txt to constants.typoscript and setup.typoscript
 * Get rid of cache deletion by the extension
 *
 * Version 7.2.0
 * -------------                    
 * Improved song search forms
 * Allows to add verses per song to the reporting
 *
 * Version 7.2.1
 * -------------                    
 * Corrected typo in reporting partial "SongTable.html"
 *
 * Version 7.2.2
 * -------------                    
 * Corrected link in reporting template "List.html"
 *
**/